### ISSUE TITLE
AttributeError: 'MemoryTempfile' object has no attribute 'tempdir'

### ISSUE THREAD

**Issue by goldyfruit** [OpenVoiceOS/ovos-messagebus#12]
When starting the service on Mac OS (Python 3.11) without any `mycroft.conf`.
```
'MemoryTempfile' object has no attribute 'tempdir'
Traceback (most recent call last):
  File "/Users/goldyfruit/Virtualenvs/ovos/lib/python3.11/site-packages/combo_lock/combo_lock.py", line 117, in __init__
    path = join(get_ram_directory("combo_locks"), filename)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/goldyfruit/Virtualenvs/ovos/lib/python3.11/site-packages/combo_lock/util.py", line 7, in get_ram_directory
    path = os.path.join(tempfile.gettempdir(), folder)
                        ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/goldyfruit/Virtualenvs/ovos/lib/python3.11/site-packages/memory_tempfile/memory_tempfile.py", line 80, in gettempdir
    return self.tempdir
           ^^^^^^^^^^^^
AttributeError: 'MemoryTempfile' object has no attribute 'tempdir'
```

**Comment by goldyfruit** [comment]
Doesn't seem to be related to this service only. I got the same when starting ` ovos-dinkum-listener`.

```
(ovos) goldyfruit@Gaetans-Air ~ % ~/Virtualenvs/ovos/bin/ovos-dinkum-listener 
'MemoryTempfile' object has no attribute 'tempdir'
Traceback (most recent call last):
  File "/Users/goldyfruit/Virtualenvs/ovos/lib/python3.11/site-packages/combo_lock/combo_lock.py", line 117, in __init__
    path = join(get_ram_directory("combo_locks"), filename)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/goldyfruit/Virtualenvs/ovos/lib/python3.11/site-packages/combo_lock/util.py", line 7, in get_ram_directory
    path = os.path.join(tempfile.gettempdir(), folder)
                        ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/goldyfruit/Virtualenvs/ovos/lib/python3.11/site-packages/memory_tempfile/memory_tempfile.py", line 80, in gettempdir
    return self.tempdir
           ^^^^^^^^^^^^
AttributeError: 'MemoryTempfile' object has no attribute 'tempdir'
2023-05-26 16:04:38.621 - OVOS - ovos_utils.configuration:get_xdg_config_save_path:141 - WARNING - configuration moved to the `ovos_config` package. This submodule will be removed in ovos_utils 0.1.0
2023-05-26 16:04:38.683 - OVOS - ovos_utils.configuration:get_xdg_base:76 - WARNING - configuration moved to the `ovos_config` package. This submodule will be removed in ovos_utils 0.1.0
'MemoryTempfile' object has no attribute 'tempdir'
Traceback (most recent call last):
  File "/Users/goldyfruit/Virtualenvs/ovos/lib/python3.11/site-packages/combo_lock/combo_lock.py", line 117, in __init__
    path = join(get_ram_directory("combo_locks"), filename)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/goldyfruit/Virtualenvs/ovos/lib/python3.11/site-packages/combo_lock/util.py", line 7, in get_ram_directory
    path = os.path.join(tempfile.gettempdir(), folder)
                        ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/goldyfruit/Virtualenvs/ovos/lib/python3.11/site-packages/memory_tempfile/memory_tempfile.py", line 80, in gettempdir
    return self.tempdir
           ^^^^^^^^^^^^
AttributeError: 'MemoryTempfile' object has no attribute 'tempdir'
```

**Comment by goldyfruit** [comment]
Seems to be related to the fact that Mac OS doesn't have `/dev/shm` and `memory_tempfile` seems to create files in there.

**Comment by goldyfruit** [comment]
According to their example, there is a "fallback" if the file can't be created into memory.

```python
# We now do not want to use /dev/shm or /run/shm and no ramfs paths
# If /run/user/{uid} is available, we prefer it to /tmp
# And we want to try /var/run as a last resort
# If all fails, fallback to platform's tmp dir

from memory_tempfile import MemoryTempfile
import memory_tempfile

# By the way, all paths with string {uid} will have it replaced with the user id
tempfile = MemoryTempfile(preferred_paths=['/run/user/{uid}'], remove_paths=['/dev/shm', '/run/shm'],
                          additional_paths=['/var/run'], filesystem_types=['tmpfs'], fallback=True)

if tempfile.found_mem_tempdir():
    print('We could use any of the following paths: {}'.format(tempfile.get_usable_mem_tempdir_paths()))
    print('And we are using now: {}'.format(tempfile.gettempdir()))

with tempfile.NamedTemporaryFile() as ntf:
    # use it as usual...
    pass
```

**Comment by JarbasAl** [comment]
fallback flag is passed https://github.com/forslund/combo-lock/blob/master/combo_lock/util.py#L6 ...

xfering issue to combo-lock repo

**Comment by JarbasAl** [comment]
fixed in https://github.com/forslund/combo-lock/pull/20 :)

**Comment by goldyfruit** [comment]
All good!

```
(ovos) goldyfruit@Gaetans-Air ~ % ~/Virtualenvs/ovos/bin/ovos-messagebus
2023-05-27 11:32:27.812 - bus - ovos_messagebus.__main__:main:48 - INFO - Starting message bus service...
2023-05-27 11:32:27.814 - bus - ovos_messagebus.load_config:load_message_bus_config:33 - INFO - Loading message bus configs
2023-05-27 11:32:27.824 - bus - ovos_messagebus.__main__:on_ready:32 - INFO - Message bus service started!
```

**Comment by forslund** [comment]
Thanks for testing and verifying!

**Comment by goldyfruit** [comment]
> Thanks for testing and verifying!

Thanks for fixing!!!
